server:
  port: 9003

spring:
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      username: tech-trove-user
      password: qj4peQLq
      database: user-db

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://127.0.0.1:8080/realms/tech-trove-realm"
          jwk-set-uri: "http://127.0.0.1:8080/realms/tech-trove-realm/protocol/openid-connect/certs"
